/* tslint:disable */
/* eslint-disable */
/*
XKCD

Webcomic of romance, sarcasm, math, and language.

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/


export * from './api/info-api';

