/*
XKCD

Webcomic of romance, sarcasm, math, and language.

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/

import { AxiosRequestConfig } from "axios";
import {
  InfoApi,
} from "./api";
import { Configuration, ConfigurationParameters } from "./configuration";
import { XkcdCustom } from "./client-custom";

export class Xkcd extends XkcdCustom {
  readonly info: InfoApi;

  constructor(configurationParameters: ConfigurationParameters = {}) {
    super(configurationParameters);
    const configuration = new Configuration(configurationParameters);
    this.info = new InfoApi(configuration);
  }

}
