/*
XKCD

Webcomic of romance, sarcasm, math, and language.

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface Comic
 */
export interface Comic {
    /**
     * 
     * @type {string}
     * @memberof Comic
     */
    'title'?: string;
    /**
     * 
     * @type {string}
     * @memberof Comic
     */
    'alt'?: string;
    /**
     * 
     * @type {string}
     * @memberof Comic
     */
    'day'?: string;
    /**
     * 
     * @type {string}
     * @memberof Comic
     */
    'img'?: string;
    /**
     * 
     * @type {string}
     * @memberof Comic
     */
    'link'?: string;
    /**
     * 
     * @type {string}
     * @memberof Comic
     */
    'month'?: string;
    /**
     * 
     * @type {string}
     * @memberof Comic
     */
    'news'?: string;
    /**
     * 
     * @type {number}
     * @memberof Comic
     */
    'num'?: number;
    /**
     * 
     * @type {string}
     * @memberof Comic
     */
    'safe_title'?: string;
    /**
     * 
     * @type {string}
     * @memberof Comic
     */
    'transcript'?: string;
    /**
     * 
     * @type {string}
     * @memberof Comic
     */
    'year'?: string;
}

